import express from 'express';
import cookieParser from 'cookie-parser';
import logger from 'morgan';
import cors from 'cors';
import session from 'express-session';
import mongoose from 'mongoose';
import productController from './controllers/product.controller';
import userController from './controllers/user.controller';
import threadController from './controllers/thread.controller';
import replyController from './controllers/reply.controller';
import indexRoute from './routes/index.route';
import { resource } from './routes/utils';

const dbURL =
  process.env.MONGODB_URI ||
  'mongodb://root:password1@ds243254.mlab.com:43254/forum';

mongoose.connect(
  dbURL,
  {
    useCreateIndex: true,
    useNewUrlParser: true,
  },
);
mongoose.Promise = Promise;

const db = mongoose.connection;
// eslint-disable-next-line no-console
db.on('error', console.error.bind(console, 'MongoDB connection error:'));

const app = express();

// default middleware generated by express
app.use(logger('dev'));
app.use(express.json());
app.use(express.urlencoded({ extended: false }));
app.use(cookieParser());
// app.use(express.static(path.join(__dirname, '../client/dist/index.html')));

// enable CORS
app.use(cors());

// track logins by using sessions
app.use(
  session({
    secret: process.env.SECRET || 'no u',
    resave: true,
    saveUninitialized: false,
  }),
);

// route middleware
app.use('/', indexRoute);
resource(app, '/products', productController);
resource(app, '/threads', threadController);
resource(app, '/replies', replyController);

app.post('/users/auth', userController.authenticate);
app.post('/users/validate', userController.validate);
resource(app, '/users', userController);

// 404
// TODO: change this to fit client side routing
app.get('*', (req, res, next) => {
  const err = new Error('Not Found');
  err.status = 404;
  next(err);
});

// catch all error handler
// eslint-disable-next-line no-unused-vars
app.use((err, req, res, next) => {
  res.status(err.status || 500).send();
});

module.exports = app;
